#!/usr/bin/python

import os, sys, shutil, threading

name = os.path.basename(sys.argv[0])
if not name.endswith(".validator"):
  sys.exit(1)
test = name[:-len(".validator")]

def stdin():
  shutil.copyfileobj(
    file(os.path.join(os.path.dirname(sys.argv[0]),
                               "%s.in" % test)),
    sys.stdout, 32768)
  sys.stdout.flush()
  os.close(1)

t = threading.Thread(target=stdin)
t.start()


def sort(fh):
  result = [tuple(int(y) for y in x.strip().split()) for x in fh]
  result.sort()
  return result


expected = sort(file(
    os.path.join(os.path.dirname(sys.argv[0]), "%s.out" % test)))
actual = sort(sys.stdin)
if len(expected) != len(actual):
  sys.exit(1)

for i in xrange(len(expected)):
  if expected[i] != actual[i]:
    sys.exit(1)

t.join()
